config/routes.rb
AppExemple::Application.routes.draw do
  resources :users

  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'

  root :to => 'pages#Accueil'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  nom                :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :nom, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :nom,
				:presence => true,
				:length => { :maximum => 60 }

	validates :email, 
				:presence => true,
				:format => { :with => email_regex },
				:uniqueness => { :case_sensitive => false }

	validates :password,
				:presence => true,
				:confirmation => true,
				:length => { :within => 6..40 }

	before_save :encrypt_password
	
	#retourne true si le mot de passe correspond
	def has_password?(password_soumis)
		encrypted_password == encrypt(password_soumis)
	end


	def self.authenticate(email, password_soumis)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(password_soumis)
	end

	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end
		
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end

		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def Accueil
	@titre = "Accueil"
  end

  def contact
	@titre = "contact"
  end

  def about
	@titre = "about"
  end

  def help
	@titre = "help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
	@user = User.find(params[:id])
	@titre = @user.nom
  end

  def new
	@user = User.new
	@titre = "Inscription"
  end

  def create
	@user = User.new(params[:user])
	if @user.save
		flash[:success] = "Bienvenue sur ce site Web avec RubyOnRails"
		redirect_to @user
	else
		@titre = "Inscription"
		render 'new'
	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#definition du logo
	def logo
		image_tag("logo.png",
				  :alt => "App_exemple",
				  :class => "round")
	end

	#definition d'une base de titre qui s'affiche avec '|' si le titre est defini
	def titre
	    base_titre = "App_exemple pour Ruby On Rails"
	    if @titre.nil?
    	  base_titre
    	else
      	"#{base_titre} | #{@titre}"
    	end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_entete.html.erb
<header>
<%= link_to logo, root_path %>
<nav class="round">
  <ul>
    <li><%= link_to "Accueil", root_path %></li>
    <li><%= link_to "Aide", help_path %></li>
    <li><%= link_to "Inscription", signup_path %></li>
  </ul>
</nav>
</header>

app/views/layouts/_piedpage.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "A Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/"> Nouveautes </a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'personalisation', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> <%= titre %> </title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">
		  <%= render 'layouts/entete' %>
		  <section class="round">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
		    <%= yield %>
		  </section>
		  <%= render 'layouts/piedpage' %>
		  <%= debug(params) if Rails.env.development? %>
		</div>	
	</body>
</html>

app/views/pages/A_Propos.html.erb
<h1>A Propos</h1>
<p>
	<a href="http://railstutorial.org"> Tuto pour Ruby On Rails</a>
	est un projet de livre et de screencasts pour apprendre le développement
	web avec <a href="http://rubyonrails.org"> Ruby On Rails </a>
	Ceci est la premiere application du tutoriel.
</p>

app/views/pages/Accueil.html.erb
<h1>App_exemple</h1>
<p>
	Ceci est la page d'accueil de l'appli exemple du
	<a href="http://railstutorial.org"> Tuto pour Ruby On Rails</a>
</p>

<%= link_to "S'inscrire", signup_path, :class => "signup_button round" %>

app/views/pages/Aide.html.erb
<h1>Aide</h1>
<p>
	Obtenez toute l'aide necessaire pour ce tutoriel ROR
	<a href="http://railstutorial.org/help"> ICI </a>
</p>

app/views/pages/Contact.html.erb
<h1>Contact</h1>
<p>
	Contactez le createur du Tuto pour Ruby On Rails
	<a href="http://railstutorial.org/feedback"> ICI </a>
</p>

app/views/pages/about.html.erb
<h1>A Propos</h1>
<p>
	<a href="http://railstutorial.org"> Tuto pour Ruby On Rails</a>
	est un projet de livre et de screencasts pour apprendre le développement
	web avec <a href="http://rubyonrails.org"> Ruby On Rails </a>
	Ceci est la premiere application du tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
	Contactez le createur du Tuto pour Ruby On Rails
	<a href="http://railstutorial.org/feedback"> ICI </a>
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
	Obtenez toute l'aide necessaire pour ce tutoriel ROR
	<a href="http://railstutorial.org/help"> ICI </a>
</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "erreur") %> 
        ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	  <div class="field">
		<%= f.label :nom %><br />
		<%= f.text_field :nom %>
	  </div>
	  <div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	  </div>
	  <div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	  </div>
	  <div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	  </div>
	  <div class="actions">
		<%= f.submit "Inscription" %>
	  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Info profil" >
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>	
				<%= @user.nom %>
			</h1>
		</td>
		<td class="sidebar round">
			<strong>Nom</strong> <%= @user.nom %> <br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>